kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/oliveira-shiai/spring-artemis-consumer-v2.git'
  name: spring-artemis-consumer
  namespace: app-spring
  labels:
    app: spring-artemis-consumer
    app.kubernetes.io/component: spring-artemis-consumer
    app.kubernetes.io/instance: spring-artemis-consumer
    app.kubernetes.io/name: spring-artemis-consumer
    app.kubernetes.io/part-of: spring-artemis-consumer
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'spring-artemis-consumer:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/oliveira-shiai/spring-artemis-consumer-v2.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: spring-artemis-consumer-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: spring-artemis-consumer-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
